name: CI Pipeline with Tests and Docker Build

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} #afo
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} #nin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flask
          echo "flask==2.3.2" > requirements.txt

      - name: Run unit tests
        run: pytest unit_test.py -v

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/flask-app:latest .
          docker push $DOCKER_USERNAME/flask-app:latest
